// (1) Relink the LAST visible embedded raster on artboard 5, and (2) put a REVIEW HIGHLIGHT behind every
//     figure that has text frames sitting on top of it, per her 2026-08-17 request.
//
// (1) THE RASTER IS `AB5_EXCERPT_1sisterless_11`. Identified from its PIXELS (an embedded raster has no
//     link): its seven timestamps 3:09 7:48 13:09 18:08 25:48 32:08 38:09 matched the sidecar of
//     nf9_1-sisterless__20250411_ptk_yfpcdc20_11 EXACTLY (0.0s mean error), and its 3.45:1 shape showed it
//     is the MONITORING PORTION ONLY, not the whole 1.61:1 strip -- so relinking it to the full strip PDF
//     would have swapped a 2-row excerpt for a 4-portion figure. The excerpt is now generated by
//     custom_ab5_excerpts_20260817.py, so it will rebuild itself from now on.
//     The new placement takes the embedded item's OWN bounds, so the figure does not move or resize; the
//     original is moved to the hidden `embedded_originals_20260817` layer, NOT deleted.
//
// (2) HIGHLIGHTS: a yellow halo drawn BEHIND each affected figure, on its own layer
//     `text_overlap_review_20260817`, so she can see at a glance which figures carry text and can hide or
//     delete the whole layer in one action when done. Yellow, not red/green (NOTES rule 30). The layer is
//     explicitly sent to the BACK -- doc.layers.add() inserts at index 0, i.e. the TOP, which is how a
//     previous relink ended up invisible on the wrong layer.
#target illustrator
var AIP="/Volumes/4 MB/1_DECKS/META_FIGURES_20260814.ai";
var PDF="/Volumes/4 MB/ablation_figures_20260625/_ai_relink/pdf/AB5_EXCERPT_1sisterless_11.pdf";
var HB=new File("/Volumes/4 MB/_claude_tmp/relink_hl.txt");
function beat(m){try{HB.open("a");HB.writeln(m);HB.close();}catch(e){}}
var RECTS=[
{n:"G4_sisbehav_swimmer.pdf",l:-2030.00,t:3030.00,w:1770.90,h:1902.70,c:9},
{n:"G4_zm_full__p1.pdf",l:381.40,t:6376.30,w:2407.60,h:1377.50,c:6},
{n:"G4_exhaustion_violin_journal.pdf",l:-1893.30,t:6400.50,w:1936.50,h:1425.80,c:5},
{n:"nf9_3-sisterless__20260417_ptk2_eyfp_cdc20_ablation_18__piece1.pdf",l:-7194.30,t:6702.40,w:544.00,h:318.30,c:2}
];
app.userInteractionLevel=UserInteractionLevel.DONTDISPLAYALERTS;
var doc=app.open(new File(AIP));

// ---- (1) relink the embedded excerpt --------------------------------------------------------------
var ALL=[];
function collect(c){for(var q=0;q<c.pageItems.length;q++){var it=c.pageItems[q];
  if(it.typename==="GroupItem"){collect(it);continue;} if(it.typename==="RasterItem") ALL.push(it);}}
for(var Li=0;Li<doc.layers.length;Li++) collect(doc.layers[Li]);
var keep; try{keep=doc.layers.getByName("embedded_originals_20260817");}
catch(e){keep=doc.layers.add();keep.name="embedded_originals_20260817";}
// 2026-08-17: a HIDDEN layer is also unmodifiable — moving the original into it raised Error 9024 "Cannot
// modify a layer that is locked". Unhide/unlock it for the duration; it is re-hidden at the end.
keep.visible=true; keep.locked=false;
// 2026-08-17: Error 8705 "Target layer cannot be modified" persisted on BOTH legend_bullets and figures
// even with every layer reporting locked=false. Cause: doc.activeLayer was the HIDDEN
// `embedded_originals_20260817` layer (previous scripts moved art there, and doc.layers.add() makes the new
// layer active) — Illustrator refuses to add art while the ACTIVE layer is hidden, whatever layer object
// you address. Make a visible, unlocked layer active first.
var figs=doc.layers.getByName("figures");
figs.locked=false; figs.visible=true; doc.activeLayer=figs;
beat("activeLayer set to '"+doc.activeLayer.name+"'");
var src=new File(PDF); var relinked=0;
for(var i=0;i<ALL.length;i++){
  var ri=ALL[i],lay=""; try{lay=ri.layer.name;}catch(e){continue;}
  if(lay!=="legend_bullets") continue;
  var b=ri.visibleBounds, w=b[2]-b[0], h=b[1]-b[3];
  if(Math.abs(w-1318)>10||Math.abs(h-382)>10) continue;
  if(!src.exists){beat("MISSING "+PDF);break;}
  try{ if(ri.layer.locked) ri.layer.locked=false; }catch(e){}
  // 2026-08-17: place onto `figures`, NOT back onto `legend_bullets`. Adding to legend_bullets raised
  // Error 8705 "Target layer cannot be modified" even though a lock probe reported every layer
  // locked=false — so something about that layer refuses new art. `figures` is where every other linked
  // figure on this deck lives and is known-writable; the placement geometry is identical either way.
  var tgt; try{ tgt=doc.layers.getByName("figures"); }catch(e){ tgt=doc.layers.getByName(lay); }
  // 2026-08-17: `legend_bullets` is LOCKED (Error 8705 "Target layer cannot be modified"). Unlock only for
  // the duration of the swap and RESTORE the original lock state afterwards -- her layer locking is a
  // deliberate working state and must survive this script.
  var wasLocked=false; try{ wasLocked=tgt.locked; tgt.locked=false; }catch(e){}
  var it2=tgt.placedItems.add(); it2.file=src;
  var s=Math.min(w/it2.width,h/it2.height);           // uniform: never distorts
  it2.width=it2.width*s; it2.height=it2.height*s;
  it2.left=b[0]+(w-it2.width)/2.0; it2.top=b[1]-(h-it2.height)/2.0;
  ri.move(keep,ElementPlacement.PLACEATEND); ri.hidden=true;
  try{ tgt.locked=wasLocked; }catch(e){}
  relinked++; beat("relinked AB5 excerpt at "+b[0].toFixed(0)+","+b[1].toFixed(0)+" (layer was locked="+wasLocked+")");
}
keep.visible=false;

// ---- (2) review highlights ------------------------------------------------------------------------
var hl; try{hl=doc.layers.getByName("text_overlap_review_20260817");}
catch(e){hl=doc.layers.add();hl.name="text_overlap_review_20260817";}
while(hl.pageItems.length>0) hl.pageItems[0].remove();     // idempotent: rebuild cleanly on a re-run
hl.zOrder(ZOrderMethod.SENDTOBACK);                        // BEHIND the figures
var PAD=26, made=0;
for(var k=0;k<RECTS.length;k++){
  var R=RECTS[k];
  var r=hl.pathItems.rectangle(R.t+PAD, R.l-PAD, R.w+2*PAD, R.h+2*PAD);
  r.filled=true; r.stroked=true;
  var f=new RGBColor(); f.red=255; f.green=241; f.blue=118; r.fillColor=f;      // yellow halo
  var st=new RGBColor(); st.red=245; st.green=166; st.blue=35; r.strokeColor=st; r.strokeWidth=6;
  r.name="REVIEW text-on-figure ("+R.c+"): "+R.n;
  made++;
}
beat("highlights="+made+" relinked="+relinked);
doc.save(); doc.close(SaveOptions.SAVECHANGES);
app.userInteractionLevel=UserInteractionLevel.DISPLAYALERTS;
"relinked="+relinked+" highlights="+made;
