// Clear the overlaps left by restoring her layout with corrected heights -- moving only MY figures.
// Generated by dataops/resolve_overlaps_minimal.py. Nothing on her layers is touched.
#target illustrator
var _u = app.userInteractionLevel; app.userInteractionLevel = UserInteractionLevel.DONTDISPLAYALERTS;
var LOG=[]; var PATH="/Volumes/4 MB/1_DECKS/META_FIGURES_20260814_PUBLICATION_20260820.ai";
var doc=null;
for (var d=0; d<app.documents.length; d++) if (app.documents[d].fullName.fsName===PATH) { doc=app.documents[d]; break; }
if (doc===null) doc=app.open(new File(PATH));
app.activeDocument=doc;
var placed=[];
function collect(c){for(var i=0;i<c.pageItems.length;i++){var it=c.pageItems[i];
 if(it.typename==="PlacedItem")placed.push(it); else if(it.typename==="GroupItem")collect(it);}}
collect(doc);
function idOf(it){var n="";try{if(it.file)n=decodeURI(it.file.name).replace(/\.pdf$/i,"");}catch(e){}
 if(!n){try{n=it.name;}catch(e2){}}return n;}
var M={};
M["G5_lagging_stretch_reference"]={dx:0.0,dy:-12.0};
M["G8kymo_kk_20250904_triple_ablation_8__6_8"]={dx:1800.0,dy:1800.0};
M["G8kymo_kk_20250401_ptk_yfpcdc20_28__10_9"]={dx:0.0,dy:3756.0};
M["G7kymo_20250401_ptk_yfpcdc20_28__10"]={dx:876.0,dy:876.0};
M["G7kymo_20250401_ptk_yfpcdc20_28__9"]={dx:3060.0,dy:3060.0};
M["G7kymo_20250401_ptk_yfpcdc20_28__8"]={dx:3924.0,dy:3924.0};
M["G1_area_combined_meta_trendscaled_delta_collagen_vs_3"]={dx:540.0,dy:0.0};
M["G1_area_combined_meta_trendscaled_delta_nocollagen"]={dx:-60.0,dy:-60.0};
M["G1_roundness_combined_meta_trendscaled_delta_collagen_vs_3"]={dx:0.0,dy:-60.0};
M["G1_roundness_combined_meta_trendscaled_delta_nocollagen"]={dx:0.0,dy:-60.0};
M["nf10_lagging-stretch-rebound__20260303_Mad1_Ptk_Eyfpcdc2_ablation_1metaphase_52__piece3"]={dx:0.0,dy:0.0};
M["nf10_lagging-stretch-rebound__20260303_Mad1_Ptk_Eyfpcdc2_ablation_1metaphase_52__piece2"]={dx:0.0,dy:0.0};
M["nf10_lagging-stretch-rebound__20260303_Mad1_Ptk_Eyfpcdc2_ablation_1metaphase_52__piece1"]={dx:0.0,dy:0.0};
var n=0;
for (var p=0;p<placed.length;p++){var id=idOf(placed[p]);
 if(!M.hasOwnProperty(id))continue;
 placed[p].left=placed[p].left+M[id].dx; placed[p].top=placed[p].top+M[id].dy; n++;}
LOG.push("nudged "+n+" of my figures to clear overlaps; her placements untouched");
if(n>0){var o=new IllustratorSaveOptions();o.pdfCompatible=false;doc.saveAs(new File(PATH),o);LOG.push("SAVED");}
app.userInteractionLevel=_u;
var f=new File("/Volumes/4 MB/_claude_tmp/RESOLVE_OVERLAPS_20260821.log");
f.open("w");f.write(LOG.join("\n"));f.close();
LOG.join("\n");
