"""S54/S49 — distance to the metaphase plate over time for POLAR-marked kinetochores vs PLATE-control
kinetochores. Plate line = the drawn 'meta_plate' polyline annotation. Plate KTs = the MANUAL `paired`
kt_outlines centroids with the FULLEST runs between metaphase and anaphase (converted 2026-08-03).
Polar = dark/light purple, plate-control = dark/light green."""
import sys, csv, os, json, numpy as np, matplotlib.pyplot as plt

# ---- MIXED-SOURCE STAMP (user 2026-07-22) -------------------------------------------------------
# These figures draw the polar kinetochore from the user's MANUAL marks but the plate/control
# kinetochore from TrackMate. The standing rule is one source per plot; the user approved keeping
# these mixed PROVIDED the figure says so. This stamps it on the figure itself, so it travels with
# the PNG/PDF into the deck rather than living only in a caption.
def _mixed_source_note(fig, text="MIXED SOURCE — polar/sisterless KT = MANUAL marks; plate/control KT = TrackMate tracking (user-approved 2026-07-22)"):
    try:
        fig.text(0.005, 0.002, text, fontsize=7.2, color="#b30000", ha="left", va="bottom")
    except Exception:
        pass


sys.path.insert(0,"/Volumes/4 MB/ablation_figures_20260625"); import lib
lib.apply_style()
OUT="/Volumes/4 MB/ablation_figures_20260625/group4"; SCRIPT=__file__
import os as _osR; OUT=_osR.environ.get("KT_SWEEP_OUT",OUT); _osR.makedirs(OUT,exist_ok=True)
ANN="/Volumes/4 MB/annotations"
data,_=lib.load_master_plots(); mr={r["Batch Name"]:r for r in data}
_coh=lib.assign_cohorts(); b2={b:k for k,lst in _coh.items() for b,_ in lst}   # batch -> cohort
LONG_SAMPLE="20250401 ptk_yfpcdc20_28"   # ITEM 6/11/12: ~95-min temporal outlier — excluded everywhere below
def ps(b):
    try: return float(mr.get(b,{}).get("Pixel Size (um)","") or 0.062)
    except: return 0.062
# O1/O10: displacement normalized to a fixed 20s interval (actual t_sec gap, not frame count)
INTERVAL=20.0
def disp20(dx_um,dy_um,dt):
    if dt<=0: return None
    return np.hypot(dx_um,dy_um)*(INTERVAL/dt)
def segments20(pts_um):
    """O10: group consecutive (t_sec,x_um,y_um) into ~20s segments; per segment (effective, total, t_mid)
    rate-scaled to 20s (effective=net endpoint move, total=summed sub-step path)."""
    pts=sorted(pts_um); out=[]; i=0; n=len(pts)
    while i<n-1:
        j=i; tot=0.0
        while j<n-1 and (pts[j+1][0]-pts[i][0])<INTERVAL*1.5:
            tot+=np.hypot(pts[j+1][1]-pts[j][1],pts[j+1][2]-pts[j][2]); j+=1
            if (pts[j][0]-pts[i][0])>=INTERVAL: break
        if j==i:
            j=i+1; tot=np.hypot(pts[j][1]-pts[i][1],pts[j][2]-pts[i][2])
        dt=pts[j][0]-pts[i][0]
        if dt>0:
            eff=np.hypot(pts[j][1]-pts[i][1],pts[j][2]-pts[i][2]); sc=INTERVAL/dt
            out.append((eff*sc,tot*sc,0.5*(pts[i][0]+pts[j][0])))
        i=j
    return out
# --- metaphase-plate line (px) per batch ---
plate={}
for r in csv.DictReader(open(f"{ANN}/meta_plates.csv")):
    if lib.is_prophase_ablation(r.get("batch","")): continue   # prophase excluded (no prophase group)
    try: pts=np.array(json.loads(r["points"]),float)
    except: continue
    if len(pts)>=2: plate[r["batch"].strip()]=pts
def plate_axis(pts):
    c=pts.mean(0); _,_,vt=np.linalg.svd(pts-c); d=vt[0]; n=np.array([-d[1],d[0]])
    return c,n/np.linalg.norm(n)
def dist_px(p,c,n): return abs(float(np.dot(np.array(p,float)-c,n)))
# --- polar/sisterless markings (px) per batch ---
from collections import defaultdict
polar=defaultdict(list)
for r in csv.DictReader(open(f"{ANN}/kt_points.csv")):
    if lib.is_prophase_ablation(r.get("batch","")): continue   # prophase excluded (no prophase group)
    if r["label"] in ("polar","sisterless"):
        if lib.is_mad1(r["batch"].strip()): continue
        if lib.is_misplaced_id(r.get("id","")): continue
        try: polar[r["batch"].strip()].append((float(r["t_sec"]),float(r["x"]),float(r["y"]),int(r["frame"])))
        except: pass
# --- TrackMate loader REMOVED 2026-08-04 -------------------------------------------------------
# Every series in this file now comes from her own annotations: polar/sisterless kt_points marks and
# `paired` kinetochore outlines. The last two TrackMate consumers were the unmodified-cell group
# (dropped by the user) and the ITEM7 plate group (re-sourced to the manual paired tracks), so the
# spot-CSV loader has no callers and is deleted rather than left to be picked up again by accident.

PURPLE=("#4a148c","#b39ddb"); GREEN=("#1b5e20","#a5d6a7")

# --- plate-control KTs from MANUAL outlines (USER 2026-08-03) -------------------------------------
# "the snapped circles and/or kinetochore outlines, and any other manual annotations ive made should
# automatically override anything generated by trackmate". The plate/control series used to come from
# TrackMate; it now comes from the manually traced `paired` kinetochore outlines in kt_outlines.csv
# (each row is one polygon for one KT on one frame -> its centroid is the KT position). Coverage is also
# better: 28 cells carry paired outlines vs the 13 that had usable TrackMate plate tracks.
PLATE_CTRL_MAX_UM=15.0                # see the screen in the control branch below
# IDENTITY FIX (2026-08-04): a cell carries up to FOUR `paired` outlines per frame — one per plate KT. The
# original conversion read kt_outlines.csv directly and grouped by frame-adjacency, but `frame_delta in (0,1)`
# treats a SAME-FRAME different kinetochore as a continuation, so every "trace" zig-zagged between KTs and
# every displacement was a KT-to-KT gap rather than motion. The linked file below already resolves each
# outline to a track_id (one track = one kinetochore through time), which is what these traces require.
PAIRED_TRACKS=defaultdict(lambda: defaultdict(list))   # batch -> track_id -> [(t_sec, x_px, y_px, frame)]
for r in csv.DictReader(open(f"{ANN}/KT_OUTLINE_TRACKS_20260723.csv")):
    if lib.is_prophase_ablation(r.get("batch","")): continue   # prophase excluded (no prophase group)
    if (r.get("label") or "").strip()!="paired": continue
    b=r["batch"].strip()
    if lib.is_mad1(b): continue
    try:
        PAIRED_TRACKS[b][r["track_id"]].append((float(r["t_sec"]),float(r["cx_px"]),float(r["cy_px"]),int(r["frame"])))
    except Exception:
        continue
for _b in PAIRED_TRACKS:
    for _t in PAIRED_TRACKS[_b]: PAIRED_TRACKS[_b][_t].sort()
PAIRED_OUTLINES={b:sorted(s for tr in v.values() for s in tr) for b,v in PAIRED_TRACKS.items()}  # kept: membership tests only
print(f"manual paired-KT tracks (plate controls): {len(PAIRED_TRACKS)} cells, "
      f"{sum(len(v) for v in PAIRED_TRACKS.values())} tracks, "
      f"{sum(len(s) for v in PAIRED_TRACKS.values() for s in v.values())} outlines")
# A cell no longer needs a TrackMate track to qualify: the plate controls come from manual outlines, so
# requiring `b in trkmaster` would have capped coverage at the TrackMate set and thrown away the extra cells
# the manual tracing provides (user 2026-08-03).
cells=[b for b in polar if b in plate and len(polar[b])>=8]
# ITEM 6/11/12: drop the ~95-min temporal outlier; ITEM 9: drop unassigned-cohort cells (double-chromosome /
# not in any cohort) so only real sisterless groups remain — and record which sisterless groups are present.
for b in cells:
    if b==LONG_SAMPLE: lib.log_review("long_temporal_outlier",b,"~95 min","~95-min track excluded from tracking/chronological plots (ITEM 6)")
    elif b2.get(b) is None: lib.log_review("tracking_unassigned",b,"no cohort","unassigned-cohort cell (double-chromosome/not in a cohort) excluded from tracking distance plots (ITEM 9); investigate")
cells=[b for b in cells if b!=LONG_SAMPLE and b2.get(b) is not None and not lib.excluded(b)]   # + global REVIEW_EXCLUDE outlier
from collections import Counter as _Counter
_cohcnt=_Counter(b2.get(b) for b in cells)
# human label for the sisterless groups present (ITEM 9): 1-Sister == single, 3-Sister == triple, etc.
_SISNAME={"1-Sister":"single (1-sisterless)","2-Sister":"double (2-sisterless)","3-Sister":"triple (3-sisterless)","4-Sister":"quad (4-sisterless)"}
SIS_GROUPS_LABEL=", ".join(f"{_SISNAME.get(k,k)} N={n}" for k,n in sorted(_cohcnt.items()))
print(f"tracking sisterless groups: {SIS_GROUPS_LABEL}")
fig,ax=plt.subplots(figsize=(9.5,5.6)); recD=[]; recN=[]; npol=0; nplate=0   # recN: N5 normalized-time records [batch,group,frac_meta_to_ana,dist_um]
osc_pol=[]; osc_pla=[]   # S53: per-frame displacement (µm) polar-marked vs plate-control
osc_pol_tv=[]; osc_pla_tv=[]   # S53 CHRONOLOGICAL: (batch, t_min_from_meta, displacement µm) per step
plate_spots=defaultdict(list)   # S49: selected plate-control spots (t,x_px,y_px,trackmate_total_intensity) per batch
for b in cells:
    pts=plate[b]; c,n=plate_axis(pts); pxs=ps(b)
    meta=lib.parse_time(mr.get(b,{}).get("Metaphase Start (s)","")); ana=lib.parse_time(mr.get(b,{}).get("Anaphase Onset (s)",""))
    # polar-marked KTs: distance over time (relative to metaphase if known)
    # KT IDENTITY (2026-08-04): polar[b] pools EVERY polar/sisterless mark in the cell, and a triple cell
    # carries up to 6 at once — so stepping through it in time order measured KT-to-KT gaps, not motion.
    # lib.link_kt_tracks splits the marks back into one series per kinetochore.
    _ptracks=[[(t,x,y,fr) for fr,t,x,y in tr]
              for tr in lib.link_kt_tracks([(fr,t,x,y) for t,x,y,fr in polar[b]],pxs)]
    pr=sorted(polar[b])                                 # pooled: only for per-mark (identity-free) uses
    for _tr in _ptracks:
        for (t0,x0,y0,_),(t1,x1,y1,_) in zip(_tr,_tr[1:]):   # S53 oscillation (O1: per-20s displacement)
            _d=disp20((x1-x0)*pxs,(y1-y0)*pxs,t1-t0)
            if _d is not None:
                osc_pol.append(_d); osc_pol_tv.append((b,(0.5*(t0+t1)-(meta or 0))/60,_d))
    # s62: anchor on metaphase + plot ONLY points AFTER metaphase start (every polar series starts at t=0)
    if meta is None:
        lib.log_review("polar_no_metaphase",b,"","no Metaphase Start — polar series cannot be anchored at t=0; skipped on s62");
    else:
      for _kt_i,_tr in enumerate(_ptracks):                # ONE LINE PER KINETOCHORE, never merged
        prm=[p for p in _tr if p[0]>=meta]                 # drop pre-metaphase polar points
        px=[t for t,_,_,_ in prm]; pd=[dist_px((x,y),c,n)*pxs for _,x,y,_ in prm]
        # s62: pull a polar track that oscillates abnormally — a frame-mapping error makes the distance
        # zig-zag (reverses almost every step; path length >> the range it actually covers). Detected by
        # the reversal fraction (sign flips in consecutive steps) AND the path/range ratio, so a normally
        # oscillating polar KT is kept but the broken one (e.g. 20250711 double ablation_4: flips≈0.94,
        # path/range≈30) is pulled.
        _dd=np.diff(pd); _flips=float(np.mean(np.sign(_dd[:-1])*np.sign(_dd[1:])<0)) if len(_dd)>=3 else 0.0
        _pr=float(np.sum(np.abs(_dd))/((max(pd)-min(pd))+1e-6)) if len(pd)>=3 else 0.0
        if len(pd)>=6 and _flips>=0.85 and _pr>=15:
            lib.log_review("polar_line_oscillates",b,f"flips={_flips:.2f} path/range={_pr:.0f}","polar plate-distance track zig-zags abnormally (frame-mapping error) — pulled from s62")
        elif len(px)>=3:
            lib.cell_line(ax,[(t-meta)/60 for t in px],pd,PURPLE[1],alpha=.5,lw=1,zorder=1); npol+=1
            for t,d in zip(px,pd): recD.append([b,"polar",round((t-meta)/60,2),round(d,2),f"kt{_kt_i+1}"])
            # N5: normalized time = fraction of this cell's metaphase->anaphase window (needs a usable ana>meta)
            _win=(ana-meta) if (ana is not None and ana>meta) else None
            if _win:
                for t,d in zip(px,pd): recN.append([b,"polar",round((t-meta)/_win,4),round(d,2),f"kt{_kt_i+1}"])
    # plate-control KTs: MANUAL `paired` outlines (user 2026-08-03 - manual annotations override TrackMate).
    # One traced polygon per KT per frame; the polygon centroid is the KT position. ONE TRACK PER KINETOCHORE
    # (KT_OUTLINE_TRACKS), so a cell with several paired KTs yields separate traces instead of one zig-zag
    # between them — see the identity note at the loader.
    _tracks=PAIRED_TRACKS.get(b,{})
    if _tracks and meta is not None and ana is not None:
        _runs=[[s for s in tr if meta<=s[0]<=ana] for tr in _tracks.values()]
        def mediandist(spots):
            dd=[dist_px((x,y),c,n)*pxs for _,x,y,_ in spots]; return np.median(dd) if dd else 1e9
        for _pk,ss in enumerate(sorted([r for r in _runs if len(r)>=3],key=mediandist)[:3]):
            _ktid=f"plate{_pk+1}"
            # ITEM 8 (kept): a control trace that only starts well after metaphase floats in from a random
            # mid-plot x with no connection to the t=0 origin.
            if (ss[0][0]-meta)/60 > 3.0:
                lib.log_review("plate_track_not_at_origin",b,f"starts +{(ss[0][0]-meta)/60:.1f} min","manual paired-KT control trace starts mid-plot (not connected to t=0 metaphase origin) — EXCLUDED (ITEM 8)"); continue
            for (t0,x0,y0,_),(t1,x1,y1,_) in zip(ss,ss[1:]):   # S53 oscillation (O1: per-20s displacement)
                _d=disp20((x1-x0)*pxs,(y1-y0)*pxs,t1-t0)
                if _d is not None:
                    osc_pla.append(_d); osc_pla_tv.append((b,(0.5*(t0+t1)-meta)/60,_d))
            # A plate/paired control kinetochore sits AT the plate by definition. Pooled control distances are
            # median 2.05 um, p90 5.8, p99 8.96 - so a point tens of um away is a tracing/frame-mapping
            # artefact, not biology. Drop such points (and log them) instead of letting one spike stretch the
            # whole y-axis. Threshold is deliberately far above p99.
            _dd=[dist_px((x,y),c,n)*pxs for _,x,y,_ in ss]
            _bad=[i for i,v in enumerate(_dd) if v>PLATE_CTRL_MAX_UM]
            for i in _bad:
                lib.log_review("plate_control_far_from_plate",b,f"{_dd[i]:.1f} µm @ {(ss[i][0]-meta)/60:+.1f} min",
                               f"manual paired-KT control point >{PLATE_CTRL_MAX_UM:g} µm from the plate "
                               f"(pooled p99 is 9.0 µm) — implausible for a plate-resident KT; point removed, re-check the trace")
            ss=[s for i,s in enumerate(ss) if i not in set(_bad)]
            if len(ss)<3: continue
            d=[dist_px((x,y),c,n)*pxs for _,x,y,_ in ss]
            lib.cell_line(ax,[(t-meta)/60 for t,_,_,_ in ss],d,GREEN[1],alpha=.55,lw=1,zorder=1); nplate+=1
            for (t,_,_,_),dd in zip(ss,d): recD.append([b,"plate",round((t-meta)/60,2),round(dd,2),_ktid])
            # N5: normalized time (ana already guaranteed not None in this plate branch)
            _winp=(ana-meta) if ana>meta else None
            if _winp:
                for (t,_,_,_),dd in zip(ss,d): recN.append([b,"plate",round((t-meta)/_winp,4),round(dd,2),_ktid])
            plate_spots[b].extend(ss)   # (t,x_px,y_px,tm_intensity)
# per-GROUP AVERAGE (mean) trajectory — binned MEAN over all that group's traces, distinct (bold) from the faint individual lines
_TREND_XY={}   # grp -> [(x,y)] for the trend-scaled companion (#11c)
def trend(grp,col):
    P=[(r[0],r[2],r[3]) for r in recD if r[1]==grp]
    if len(P)<5: return
    _bs=set(p[0] for p in P)                                  # #11b: cap trend at avg (anaphase-metaphase) over these cells
    _cc=[]
    for _b in _bs:
        _m=lib.parse_time(mr.get(_b,{}).get("Metaphase Start (s)","")); _an=lib.parse_time(mr.get(_b,{}).get("Anaphase Onset (s)",""))
        if _m is not None and _an is not None and _an>_m: _cc.append((_an-_m)/60.0)
    _cap=float(np.median(_cc)) if _cc else None  # USER 2026-08-10: MEDIAN, not mean
    ts=np.array([p[1] for p in P]); vs=np.array([p[2] for p in P]); bs=[p[0] for p in P]
    bx=[];by=[]
    for lo in np.arange(ts.min(),ts.max()+3,3):
        if _cap is not None and lo+1.5>_cap: break            # #11b: stop trend at avg anaphase (from metaphase)
        m=(ts>=lo)&(ts<lo+3); ncell=len({bs[j] for j in np.where(m)[0]})
        if m.sum()>=3 and ncell>=2: bx.append(lo+1.5); by.append(float(vs[m].mean()))   # AVERAGE trajectory
        elif bx: break          # s62: CAP the trend where samples drop off — don't extend into the sparse tail
    if len(bx)>=2:
        # USER 2026-08-17: shaded SEM around the group trend, in place of the per-kinetochore lines.
        # n is the number of CELLS in the bin -- the trend's own binning already requires ncell>=2.
        _p3=[(p[1],p[2],p[0]) for p in P if (_cap is None or p[1]<=_cap)]
        _sx,_sy,_ss=lib.binned_mean_sem(_p3,nb=max(2,len(bx)),lo=min(bx)-1.5,hi=max(bx)+1.5)
        if _sx and any(v>0 for v in _ss):
            ax.fill_between(_sx,[v-e for v,e in zip(_sy,_ss)],[v+e for v,e in zip(_sy,_ss)],
                            color=col,alpha=.20,lw=0,zorder=3)
        ax.plot(bx,by,color=col,lw=3,zorder=4); _TREND_XY[grp]=list(zip(bx,by))
# s53/s54: exclude an outlier on the plate-KT group (it wrecks the scaling). Flag the batch whose
# plate-distance distribution is a statistical outlier and drop it. NOTE: plate tracks load from
# the manual paired outlines; when a cell has none there are zero plate points, so this screen is
# inert (see FLAG) but becomes active once the drive remounts.
_plate_by_b=defaultdict(list)
for r in recD:
    if r[1]=="plate": _plate_by_b[r[0]].append(r[3])
if len(_plate_by_b)>=5:
    _med=[(b,float(np.median(v))) for b,v in _plate_by_b.items()]
    _keepb={b for b,_ in lib.iqr_outliers("s53_plate_dist_outlier",_med)}
    _exb=[b for b,_ in _med if b not in _keepb]
    if _exb: recD=[r for r in recD if not (r[1]=="plate" and r[0] in _exb)]; print(f"s53/s54 plate-KT outlier batches excluded: {_exb}")
trend("polar",PURPLE[0]); trend("plate",GREEN[0])
ax.axvline(0,color="#333",ls=":",lw=.8); ax.set_xlabel("Time from metaphase (min)"); ax.set_ylabel("Distance to metaphase plate (µm)")
from matplotlib.lines import Line2D
import matplotlib.patheffects as pe
ax.legend(handles=[Line2D([0],[0],color=PURPLE[0],lw=3,label=f"polar-marked KTs — group mean (N={npol})"),
                   Line2D([0],[0],color=PURPLE[1],lw=1,label=("polar-marked (individual kinetochores)" if lib.PERCELL_LINES else "polar-marked — shaded = SEM")),
                   Line2D([0],[0],color=GREEN[0],lw=3,label=f"plate-control KTs — group mean (N={nplate})"),
                   Line2D([0],[0],color=GREEN[1],lw=1,label=("plate-control (individual kinetochores)" if lib.PERCELL_LINES else "plate-control — shaded = SEM"))],fontsize=8)
ax.set_title(f"Distance to metaphase plate (after metaphase start) — polar-marked vs plate-control KTs\nsisterless groups: {SIS_GROUPS_LABEL} · {npol} of {len(cells)} polar cells plotted",loc="left",fontweight="bold",fontsize=9.3)
# O8 troubleshoot note: WHY the plate-control (green) traces are shorter than the polar (purple) ones.
ax.text(0.0,-0.16,("Plate-control traces are shorter because they come from the manual paired outlines, restricted to each cell's metaphase to anaphase window and\n"
                   "to the 3 fullest tracks nearest the plate. The user expected a same-frame MANUAL plate mark per polar mark, but kt_points.csv has\n"
                   "only 84 'paired_kt' marks across 5 cells (vs 854 polar) — those annotations are largely missing, so a matched-length manual\n"
                   "plate group can't be built yet. Add paired plate KT annotations in the annotation slides to lengthen/align the plate traces."),
        transform=ax.transAxes,fontsize=6.4,va="top",ha="left",bbox=dict(boxstyle="round,pad=0.4",fc="#fff8e1",ec="#e0c060",alpha=.95))
plt.tight_layout(); plt.savefig(f"{OUT}/G4_plate_distance_tracking.png",bbox_inches="tight"); plt.close()
# ---- #11c: trendline-SCALED companion (axes fit the polar/plate trends; individual tracks may run off-plot) ----
if _TREND_XY:
    figT,axT=plt.subplots(figsize=(9.5,5.6)); _colmap={"polar":(PURPLE[0],PURPLE[1]),"plate":(GREEN[0],GREEN[1])}
    _cellT=defaultdict(list)
    for r in recD: _cellT[(r[1],r[0])].append((r[2],r[3]))
    for (grp,b),ser in _cellT.items():
        ser=sorted(ser); c=_colmap.get(grp,("#888","#ccc"))[1]
        if len(ser)>=2: lib.cell_line(axT,[s[0] for s in ser],[s[1] for s in ser],c,alpha=.4,lw=.9,zorder=1)
    _tx=[];_ty=[]
    for grp,xy in _TREND_XY.items():
        c=_colmap.get(grp,("#888",))[0]
        axT.plot([p[0] for p in xy],[p[1] for p in xy],color=c,lw=3,zorder=5); _tx+=[p[0] for p in xy]; _ty+=[p[1] for p in xy]
    if _tx:
        _mx=(max(_tx)-min(_tx))*0.06+1; _my=(max(_ty)-min(_ty))*0.12+0.5
        axT.set_xlim(min(_tx)-_mx,max(_tx)+_mx); axT.set_ylim(min(_ty)-_my,max(_ty)+_my)
    axT.axvline(0,color="#333",ls=":",lw=.8); axT.set_xlabel("Time from metaphase (min)"); axT.set_ylabel("Distance to metaphase plate (µm)")
    axT.legend(handles=[Line2D([0],[0],color=PURPLE[0],lw=3,label="polar-marked KTs — mean"),Line2D([0],[0],color=GREEN[0],lw=3,label="plate-control KTs — mean")],fontsize=8)
    axT.set_title(f"Distance to metaphase plate — TREND-SCALED (axes fit trend lines; individual tracks may run off-plot)\nsisterless groups: {SIS_GROUPS_LABEL}",loc="left",fontweight="bold",fontsize=9)
    plt.tight_layout(); plt.savefig(f"{OUT}/G4_plate_distance_tracking_trendscaled.png",bbox_inches="tight"); plt.close()
    # trend-scaled companion replots the SAME per-track data (recD) with axes fit to the trends -> identical data CSV
    lib.record_plot("G4_plate_distance_tracking_trendscaled",["batch","group","t_min_from_meta","dist_to_plate_um","kt"],recD,
      {"type":"distance-to-plate over time, TREND-SCALED (axes fit trend lines)","polar":"kt_points polar/sisterless markings, SPLIT PER KINETOCHORE (lib.link_kt_tracks)",
       "plate":"MANUAL paired kt_outlines centroids, fullest runs between meta&ana","companion_of":"G4_plate_distance_tracking"},SCRIPT,"Distance to plate: polar vs plate-control (trend-scaled)")
    print("plate-distance-tracking trend-scaled companion -> G4_plate_distance_tracking_trendscaled.png")
lib.record_plot("G4_plate_distance_tracking",["batch","group","t_min_from_meta","dist_to_plate_um","kt"],recD,
  {"type":"distance-to-plate over time","polar":"kt_points polar/sisterless markings, SPLIT PER KINETOCHORE (lib.link_kt_tracks)","plate":"MANUAL paired kt_outlines centroids, fullest runs between meta&ana",
   "plate_line":"meta_plate polyline (PCA axis, perpendicular distance)"},SCRIPT,"Distance to plate: polar-marked vs plate-control KTs")
print(f"plate-distance tracking: {len(cells)} cells, polar tracks={npol}, plate tracks={nplate}, {len(recD)} points")

# ===== N5: NORMALIZED-TIME companion of the distance-to-plate plot =====
# Same per-group trends/legend as the absolute-minutes version, but x = fraction of EACH cell's
# metaphase->anaphase window (0 = metaphase onset, 1 = anaphase onset). Per-cell normalization needs
# the cell's Metaphase Start + Anaphase Onset (lib.parse_time from master); cells without a usable
# meta->ana window (ana<=meta or missing ana) are absent from recN. This puts every KT trajectory on a
# common 0->1 mitotic-progress axis. Mirror the same s53/s54 plate-outlier exclusion applied to recD.
if '_exb' in dir() and _exb:
    recN=[r for r in recN if not (r[1]=="plate" and r[0] in _exb)]
_polN_cells=sorted({r[0] for r in recN if r[1]=="polar"}); _plaN_cells=sorted({r[0] for r in recN if r[1]=="plate"})
_winN_cells=sorted({r[0] for r in recN})   # cells with a usable meta->ana window contributing to recN
figN,axN=plt.subplots(figsize=(9.5,5.6)); _npolN=0; _nplaN=0
for b in _polN_cells:
    for _k in sorted({r[4] for r in recN if r[1]=="polar" and r[0]==b}):   # one line PER KINETOCHORE
        P=sorted((r[2],r[3]) for r in recN if r[1]=="polar" and r[0]==b and r[4]==_k)
        if len(P)>=3: lib.cell_line(axN,[p[0] for p in P],[p[1] for p in P],PURPLE[1],alpha=.5,lw=1,zorder=1); _npolN+=1
for b in _plaN_cells:
    for _k in sorted({r[4] for r in recN if r[1]=="plate" and r[0]==b}):
        P=sorted((r[2],r[3]) for r in recN if r[1]=="plate" and r[0]==b and r[4]==_k)
        if len(P)>=3: lib.cell_line(axN,[p[0] for p in P],[p[1] for p in P],GREEN[1],alpha=.55,lw=1,zorder=1); _nplaN+=1
_NTREND={}
def trendN(grp,col):   # binned MEAN over 0..1 normalized progress (bin width 0.1), >=2 cells per bin
    P=[(r[0],r[2],r[3]) for r in recN if r[1]==grp]
    if len(P)<5: return
    ts=np.array([p[1] for p in P]); vs=np.array([p[2] for p in P]); bs=[p[0] for p in P]
    bx=[];by=[]
    for lo in np.arange(0,1.0,0.1):
        m=(ts>=lo)&(ts<lo+0.1); ncell=len({bs[j] for j in np.where(m)[0]})
        if m.sum()>=3 and ncell>=2: bx.append(lo+0.05); by.append(float(vs[m].mean()))
    if len(bx)>=2: axN.plot(bx,by,color=col,lw=3,zorder=4); _NTREND[grp]=(bx,by,col)
trendN("polar",PURPLE[0]); trendN("plate",GREEN[0])
axN.axvline(0,color="#333",ls=":",lw=.8); axN.set_xlim(0,1)
axN.set_xlabel("Fraction of metaphase elapsed"); axN.set_ylabel("Distance to metaphase plate (µm)")
axN.legend(handles=[Line2D([0],[0],color=PURPLE[0],lw=3,label=f"polar-marked KTs — group mean (N={_npolN} kinetochores)"),
                    Line2D([0],[0],color=PURPLE[1],lw=1,label=("polar-marked (individual kinetochores)" if lib.PERCELL_LINES else "polar-marked — shaded = SEM")),
                    Line2D([0],[0],color=GREEN[0],lw=3,label=f"plate-control KTs — group mean (N={_nplaN} kinetochores)"),
                    Line2D([0],[0],color=GREEN[1],lw=1,label=("plate-control (individual kinetochores)" if lib.PERCELL_LINES else "plate-control — shaded = SEM"))],fontsize=8)
axN.set_title(f"Distance to metaphase plate vs normalized mitotic progress — polar-marked vs plate-control KTs ({len(_winN_cells)} cells with usable meta-to-ana window)",loc="left",fontweight="bold",fontsize=9.5)
plt.tight_layout(); plt.savefig(f"{OUT}/G4_plate_distance_time_normalized.png",bbox_inches="tight"); plt.close()
lib.record_plot("G4_plate_distance_time_normalized",["batch","group","frac_meta_to_ana","dist_to_plate_um","kt"],recN,
  {"type":"distance-to-plate vs normalized time (0=meta onset,1=ana onset)","polar":"kt_points polar/sisterless markings, SPLIT PER KINETOCHORE (lib.link_kt_tracks)",
   "plate":"MANUAL paired kt_outlines centroids, fullest runs between meta&ana","norm":"per-cell (t-meta)/(ana-meta) from master event times"},
  SCRIPT,"Distance to plate vs normalized mitotic progress: polar-marked vs plate-control KTs")
# #11c: trend-scaled companion (axes fit the group trends; individual tracks may run off-plot)
if _NTREND:
    # USER 2026-08-03: the wildly oscillating track is removed from THIS companion as well. Filter recN for
    # this figure only and RECOMPUTE the trends from the kept points - reusing _NTREND would have drawn a
    # trend that still contained the very track the figure claims to have dropped.
    _exclNT=lib.manual_plot_exclusions("G4_plate_distance_time_normalized_trendscaled")
    _recNT=[r for r in recN if r[0] not in _exclNT]
    for _b in sorted(_exclNT & {r[0] for r in recN}):
        lib.log_review("G4_plate_distance_time_normalized_trendscaled",_b,"",
                       "removed from this plot per MANUAL_PLOT_EXCLUSIONS.csv (user 2026-08-03); trends recomputed without it")
    figNT,axNT=plt.subplots(figsize=(9.5,5.6)); _colN={"polar":(PURPLE[0],PURPLE[1]),"plate":(GREEN[0],GREEN[1])}
    for grp in ("polar","plate"):
        for b in sorted({r[0] for r in _recNT if r[1]==grp}):
            P=sorted((r[2],r[3]) for r in _recNT if r[1]==grp and r[0]==b)
            if len(P)>=3: lib.cell_line(axNT,[p[0] for p in P],[p[1] for p in P],_colN[grp][1],alpha=.5,lw=1,zorder=1)
    _tx=[];_ty=[]
    for grp,(_ob,_oy,col) in _NTREND.items():
        _pts=[(r[2],r[3]) for r in _recNT if r[1]==grp]
        if len(_pts)<6: continue
        _px=np.array([p[0] for p in _pts]); _py=np.array([p[1] for p in _pts])
        _edges=np.linspace(0,1,11); bx=[];by=[]
        for _i in range(10):
            _m=(_px>=_edges[_i])&(_px<_edges[_i+1]) if _i<9 else (_px>=_edges[_i])&(_px<=_edges[_i+1])
            if _m.sum()>=3: bx.append((_edges[_i]+_edges[_i+1])/2); by.append(float(np.mean(_py[_m])))
        if len(bx)<2: continue
        axNT.plot(bx,by,color=col,lw=3,zorder=5); _tx+=bx; _ty+=by
    if _ty:
        _my=(max(_ty)-min(_ty))*0.15+0.5; axNT.set_ylim(min(_ty)-_my,max(_ty)+_my)
    axNT.set_xlim(0,1); axNT.set_xlabel("Fraction of metaphase elapsed"); axNT.set_ylabel("Distance to metaphase plate (µm)")
    axNT.legend(handles=[Line2D([0],[0],color=PURPLE[0],lw=3,label="polar-marked KTs — mean"),Line2D([0],[0],color=GREEN[0],lw=3,label="plate-control KTs — mean")],fontsize=8)
    axNT.set_title("Distance to plate vs normalized progress — TREND-SCALED (axes fit trend lines; individual tracks may run off-plot)",loc="left",fontweight="bold",fontsize=9.3)
    plt.tight_layout(); plt.savefig(f"{OUT}/G4_plate_distance_time_normalized_trendscaled.png",bbox_inches="tight"); plt.close()
    # trend-scaled companion replots the SAME normalized-time data (recN) with axes fit to the trends -> identical data CSV
    lib.record_plot("G4_plate_distance_time_normalized_trendscaled",["batch","group","frac_meta_to_ana","dist_to_plate_um"],_recNT,
      {"type":"distance-to-plate vs normalized time, TREND-SCALED (axes fit trend lines)","polar":"kt_points polar/sisterless markings, SPLIT PER KINETOCHORE (lib.link_kt_tracks)",
       "plate":"MANUAL paired kt_outlines centroids, fullest runs between meta&ana","norm":"per-cell (t-meta)/(ana-meta)","companion_of":"G4_plate_distance_time_normalized"},
      SCRIPT,"Distance to plate vs normalized progress: polar vs plate-control (trend-scaled)")
    print("normalized trend-scaled companion -> G4_plate_distance_time_normalized_trendscaled.png")
print(f"N5 normalized distance-to-plate: {len(recN)} points, {len(_winN_cells)} cells with usable meta->ana window (polar {_npolN}, plate {_nplaN})")

# ---- task I8 group REMOVED (USER 2026-08-04) ----
# The unmodified-cell KT group was the only TrackMate-sourced series left in this figure, and no manual
# outlines exist for unmodified cells to convert it to (all 96 unModified-cohort cells have zero
# kt_outlines rows). Rather than keep one automated group beside two manual ones, the user dropped it:
# "no need to include unmodified in that plot. that should rid it of trackmate". G4_oscillation_tracking
# is now polar-marked vs plate-control, both from her own annotations.
osc_unmod=[]; osc_unmod_eff=[]; n_unmod_cells=0; n_unmod_avail=0

# ===== ITEM 7: RECONCILE the polar & plate oscillation with G4_oscillation (group4_movement.py) =====
# The polar-marked and plate-control per-frame displacements MUST match between this figure and
# G4_oscillation. The earlier osc_pol/osc_pla above used a slightly different recipe (polar+sisterless
# merged, no frame-gap normalization, 10 µm cap, and only the plate+trackmate cell subset), which is why
# the two figures disagreed. Recompute BOTH here with movement.py's EXACT method so they are identical.
OSC_HI=8.0
_trk2=defaultdict(lambda: defaultdict(list))
for r in csv.DictReader(open(f"{ANN}/kt_points.csv")):
    if lib.is_prophase_ablation(r.get("batch","")): continue   # prophase excluded (no prophase group)
    lab=r["label"].strip()
    if lab not in ("polar","sisterless"): continue
    if lib.is_mad1(r["batch"].strip()) or lib.is_misplaced_id(r.get("id","")): continue
    try: _trk2[r["batch"].strip()][lab].append((int(r["frame"]),float(r["t_sec"]),float(r["x"]),float(r["y"])))
    except: pass
def _sister2(b):
    a=_trk2[b].get("polar",[]); c=_trk2[b].get("sisterless",[])
    return sorted(a if len(a)>=len(c) else c)
_usable2=[b for b in _trk2 if len(_sister2(b))>=5 and b2.get(b) is not None and b!=LONG_SAMPLE]
osc_pol=[]; _exb2=set(); osc_pol_eff=[]; osc_pla_eff=[]        # match movement: polar step >8µm/20s flags the whole batch out of the plate set; *_eff = O10 effective/net per 20s
for b in _usable2:
    _meta=lib.parse_time(mr.get(b,{}).get("Metaphase Start (s)",""))   # for user-flagged per-point exclusion
    # KT IDENTITY (2026-08-04): split per kinetochore before stepping — matches group4_movement exactly,
    # which is the whole point of this reconciliation block.
    for tr in lib.link_kt_tracks(_sister2(b),ps(b)):
        for (f0,t0,x0,y0),(f1,t1,x1,y1) in zip(tr,tr[1:]):
            if f1==f0: continue
            d=disp20((x1-x0)*ps(b),(y1-y0)*ps(b),t1-t0)   # O1: 20s-normalized
            if d is None: continue
            if lib.osc_point_excluded(b,(0.5*(t0+t1)-(_meta or 0))/60): continue   # user-flagged oscillation outlier — REMOVED everywhere
            if d<=OSC_HI: osc_pol.append(d)
            else: _exb2.add(b)
        for (e,_t,_m) in segments20([(t,x*ps(b),y*ps(b)) for (f,t,x,y) in tr]):   # O10 effective (net per 20s)
            if lib.osc_point_excluded(b,(_m-(_meta or 0))/60): continue   # user-flagged oscillation outlier — REMOVED everywhere
            if e<=OSC_HI: osc_pol_eff.append(e)
_OSC_EXCL=_exb2|{LONG_SAMPLE}
def _plate_axis2(b):
    pts=plate.get(b)
    if pts is None or len(pts)<2: return None
    c=pts.mean(axis=0); v=pts[-1]-pts[0]; nrm=np.hypot(*v)
    if nrm<1e-6: return None
    dd=v/nrm; return c,np.array([-dd[1],dd[0]])
osc_pla=[]
for b in plate:
    if b in _OSC_EXCL or b2.get(b) is None: continue   # ITEM 7: drop unassigned cohort from plate group too (matches group4_movement)
    # 2026-08-04: was load_tracks(b) (TrackMate) — which is why this block reported a different plate N
    # than G4_oscillation despite claiming to reconcile with it. Same manual paired tracks as everywhere else.
    ax_=_plate_axis2(b); tr=PAIRED_TRACKS.get(b,{})
    if ax_ is None or not tr: continue
    c2,nrml=ax_
    meta=lib.parse_time(mr.get(b,{}).get("Metaphase Start (s)","")); ana=lib.parse_time(mr.get(b,{}).get("Anaphase Onset (s)",""))
    if meta is None: continue
    hi=ana if (ana is not None and ana>meta) else meta+1e9
    def _nspan(sp): return sum(1 for t,x,y,_ in sp if meta<=t<=hi)
    def _mdist(sp):
        dd=[abs(np.dot(np.array([x,y])-c2,nrml))*ps(b) for t,x,y,_ in sp if meta<=t<=hi]; return np.median(dd) if dd else 1e9
    spans=[_nspan(s) for s in tr.values()]; span_med=(np.median(spans) if spans else 1) or 1
    full=[(tid,sp) for tid,sp in tr.items() if _nspan(sp)>=max(3,span_med)]
    for tid,sp in sorted(full,key=lambda kv:_mdist(kv[1]))[:3]:
        ss=[s for s in sorted(sp) if meta<=s[0]<=hi]
        for (t0,x0,y0,_),(t1,x1,y1,_) in zip(ss,ss[1:]):
            d=disp20((x1-x0)*ps(b),(y1-y0)*ps(b),t1-t0)   # O1: 20s-normalized
            if d is not None and d<=OSC_HI: osc_pla.append(d)
        for (e,_t,_m) in segments20([(t,x*ps(b),y*ps(b)) for (t,x,y,_) in ss]):   # O10 effective (net per 20s)
            if e<=OSC_HI: osc_pla_eff.append(e)
print(f"ITEM7 reconciled oscillation: polar N={len(osc_pol)} (matches G4_oscillation), plate N={len(osc_pla)}")
# O7 TROUBLESHOOT (why 515 polar steps vs 163 plate; why only 11 cells): the two groups come from DIFFERENT
# sources. Polar steps = every consecutive MANUAL polar/sisterless annotation across the whole track, for all
# annotated cells. Plate steps = only the top-3 fullest MANUAL paired-outline runs, restricted to the metaphase to anaphase
# window, for the subset of cells that have BOTH paired outlines AND master meta+ana times. The user expects
# (Both groups are MANUAL as of 2026-08-04 — the plate side comes from her traced `paired` outlines, so the
# count mismatch is coverage/windowing, NOT a difference in source.)
_pol_cells=len(_usable2); _pla_cells=len({b for b in plate if b not in _OSC_EXCL and b2.get(b) is not None and PAIRED_TRACKS.get(b)})
lib.log_review("oscillation_polar_vs_plate_count","(tracking)",f"polar {len(osc_pol)} steps/{_pol_cells} cells vs plate {len(osc_pla)} steps",
  "polar = all manual annotation steps (all cells); plate = top-3 manual paired-outline runs within meta to ana only (needs paired outlines+meta+ana). Manual paired plate marks are largely absent (84 paired_kt / 5 cells) — add them to build a same-frame manual plate group")

# ===== S53 / I8: oscillation — polar-marked vs plate-control vs unmodified-cell KTs =====
from scipy import stats as _st
fig2,ax2=plt.subplots(figsize=(7.4,5.2))
grp=[("polar-marked\nKTs",osc_pol,PURPLE[0]),("plate-control\nKTs",osc_pla,GREEN[0])]   # both MANUAL (unmodified/TrackMate group dropped 2026-08-04)
_gvals=[]   # O7: keep each group's filtered full distribution for the all-pairs stats grid
for i,(lab,vals,col) in enumerate(grp):
    vals=[v for v in vals if v is not None and v<10]   # drop tracking-jump outliers (>10µm/step)
    _gvals.append((lab.replace("\n"," ").strip(),vals))
    if len(vals)>=2:
        for bd in ax2.violinplot([vals],positions=[i],widths=.7,showextrema=False)['bodies']:
            bd.set_facecolor(col); bd.set_alpha(.3); bd.set_edgecolor(col)
    if vals:
        # O7: subsample the SCATTER to 500 points (violin body + median/mean/stats still use the full set).
        _scv=vals if len(vals)<=500 else list(np.random.RandomState(42).choice(np.array(vals),500,replace=False))
        ax2.scatter(np.full(len(_scv),i)+(np.random.RandomState(i).rand(len(_scv))-.5)*.2,_scv,s=lib.VIOLIN_DOT_S,color=col,alpha=lib.VIOLIN_DOT_ALPHA_DENSE,zorder=2)
        ax2.hlines(np.median(vals),i-.3,i+.3,color=col,lw=2.6,zorder=3)                       # median (solid)
        ax2.hlines(np.mean(vals),i-.24,i+.24,color=col,lw=1.3,ls=(0,(2,1.5)),zorder=3)        # s60: mean (dashed)
    else:
        ax2.text(i,0,"no data",ha="center",va="bottom",fontsize=7.5,color="#999")
# X1/O7 overlap fix: per-violin N/median labels go ABOVE the data at a common height (with axis headroom), not
# on the violin bodies. Compute a shared top from all groups' 99th pct.
_allv=[v for _,vv in _gvals for v in vv]
if _allv:
    _top=np.percentile(_allv,99)*1.06+0.4; ax2.set_ylim(top=_top*1.32)   # extra headroom so the all-pairs stats box clears both the N labels and the polar violin tail
    for i,(_,vals) in enumerate(_gvals):
        if vals:
            _sh=f"\n({min(len(vals),500)} of {len(vals)} shown)" if len(vals)>500 else ""
            ax2.text(i,_top,f"x̄ {np.mean(vals):.2f}\nmed {np.median(vals):.2f}\nN={len(vals)}{_sh}",ha="center",va="bottom",fontsize=7.5)
# O7: stats between ALL groups (pairwise Mann–Whitney), shown as a small grid box (not marks over the violins)
_stat_lines=[]
for a in range(len(_gvals)):
    for c in range(a+1,len(_gvals)):
        (la,va),(lc,vc)=_gvals[a],_gvals[c]
        if len(va)>=2 and len(vc)>=2:
            try: _pp=_st.mannwhitneyu(va,vc,alternative="two-sided").pvalue; _stat_lines.append(f"{la} vs {lc}: p={_pp:.2g}")
            except Exception: pass
if _stat_lines:
    # O7/2026-07-07: the box previously sat top-LEFT (axes .02,.98) directly over the polar violin (x=0),
    # clipping its upper tail. It then moved to x=1.5 — the gap between the plate-control and unmodified
    # violins. With the unmodified group dropped (2026-08-04) x=1.5 is off the right-hand edge and lands on
    # the legend, so it returns to x=0.5: the gap BETWEEN the two remaining violins, above both their tails
    # and clear of the per-group N labels at x=0 / x=1.
    ax2.text(0.5,0.985,"Mann–Whitney (all pairs):\n"+"\n".join(_stat_lines),transform=ax2.get_xaxis_transform(),
             ha="center",va="top",fontsize=6.6,
             bbox=dict(boxstyle="round,pad=0.35",fc="#f7f7f7",ec="#bbb",alpha=.92),zorder=10)
ax2.set_xticks([0,1]); ax2.set_xticklabels(["polar-marked","plate-control"]); ax2.set_ylabel("Displacement per 20s interval (µm)")
# legend mapping every colour/line
from matplotlib.lines import Line2D as _L2; from matplotlib.patches import Patch as _P2
ax2.legend(handles=[_P2(facecolor=PURPLE[0],alpha=.3,edgecolor=PURPLE[0],label=f"polar-marked KTs (kt_points; N={len([v for v in osc_pol if v<10])} steps)"),
                    _P2(facecolor=GREEN[0],alpha=.3,edgecolor=GREEN[0],label=f"plate-control KTs (manual paired outlines; N={len([v for v in osc_pla if v<10])} steps)"),
                    _L2([0],[0],color="#444",lw=2.6,label="median"),
                    _L2([0],[0],color="#444",lw=1.3,ls=(0,(2,1.5)),label="mean")],fontsize=7,loc="upper left",bbox_to_anchor=(1.01,1.0))   # legend OUTSIDE the axes (no violin/text overlap)
ax2.set_title("Kinetochore oscillation — displacement per 20s: polar-marked vs plate-control KTs\n(both from manual annotations; reconciled to match G4_oscillation; scatter subsampled to 500; Mann–Whitney)",loc="left",fontweight="bold",fontsize=9.3)
plt.tight_layout(); plt.savefig(f"{OUT}/G4_oscillation_tracking.png",bbox_inches="tight"); plt.close()
# data CSV (per-step displacement per group) — so the reconcile-to-G4_oscillation + subsample are verifiable
_osrows=[["polar-marked",round(v,3)] for v in osc_pol]+[["plate-control",round(v,3)] for v in osc_pla]
lib.record_plot("G4_oscillation_tracking",["group","per_frame_displacement_um"],_osrows,
    {"type":"violin+scatter, 2 groups (both manual)","scatter_subsample":"500 per group (violin/stats use full set)",
     "polar_N":len(osc_pol),"plate_N":len(osc_pla)},SCRIPT,"Oscillation tracking: polar-marked vs plate-control KTs (both manual)")
print(f"oscillation: polar steps={len(osc_pol)}, plate steps={len(osc_pla)} (both manual; unmodified/TrackMate group dropped)")

# ===== O10: EFFECTIVE (net endpoint) displacement per 20s — the OTHER method, companion to G4_oscillation_tracking =====
# G4_oscillation_tracking sums straight-line steps (≈ TOTAL path per interval). This companion uses net
# endpoint-to-endpoint displacement per ~20s segment (ignores back-and-forth) for the same three groups.
figEff,axEff=plt.subplots(figsize=(7.4,5.2))
_effgrp=[("polar-marked\nKTs",[v for v in osc_pol_eff if v<10],PURPLE[0]),
         ("plate-control\nKTs",[v for v in osc_pla_eff if v<10],GREEN[0]),
        ]
_efftops=[np.percentile(vv,99) for _,vv,_ in _effgrp if len(vv)>=2]
_efftop=(max(_efftops)*1.06+0.4) if _efftops else 1.0
for i,(lab,vals,col) in enumerate(_effgrp):
    if len(vals)>=2:
        for bd in axEff.violinplot([vals],positions=[i],widths=.7,showextrema=False)['bodies']:
            bd.set_facecolor(col); bd.set_alpha(.3); bd.set_edgecolor(col)
        _scv=vals if len(vals)<=500 else list(np.random.RandomState(7).choice(np.array(vals),500,replace=False))
        axEff.scatter(np.full(len(_scv),i)+(np.random.RandomState(i).rand(len(_scv))-.5)*.2,_scv,s=lib.VIOLIN_DOT_S,color=col,alpha=lib.VIOLIN_DOT_ALPHA_DENSE,zorder=2)
        axEff.hlines(np.median(vals),i-.3,i+.3,color=col,lw=2.6,zorder=3); axEff.hlines(np.mean(vals),i-.24,i+.24,color=col,lw=1.3,ls=(0,(2,1.5)),zorder=3)
        axEff.text(i,_efftop,f"x̄ {np.mean(vals):.2f}\nmed {np.median(vals):.2f}\nN={len(vals)}",ha="center",va="bottom",fontsize=7.5)
    else:
        axEff.text(i,0,"no data",ha="center",va="bottom",fontsize=7.5,color="#999")
if _efftops: axEff.set_ylim(top=_efftop*1.18)
axEff.set_xticks([0,1]); axEff.set_xticklabels(["polar-marked","plate-control"]); axEff.set_ylabel("Effective (net) displacement per 20s interval (µm)")
axEff.set_title("Kinetochore oscillation — EFFECTIVE (net endpoint) displacement per 20s (O10 companion to G4_oscillation_tracking)\nnet start to end move per ~20s segment; ignores back-and-forth (vs the per-step/total-path version)",loc="left",fontweight="bold",fontsize=9)
plt.tight_layout(); plt.savefig(f"{OUT}/G4_oscillation_tracking_effective.png",bbox_inches="tight"); plt.close()
lib.record_plot("G4_oscillation_tracking_effective",["group","effective_disp_um_per_20s"],
  [["polar-marked",round(v,3)] for v in osc_pol_eff]+[["plate-control",round(v,3)] for v in osc_pla_eff],
  {"type":"violin, 3 groups (effective/net per 20s)","method":"net endpoint per ~20s segment (O10 'other method')","companion_of":"G4_oscillation_tracking"},SCRIPT,"Effective (net) displacement per 20s — O10 tracking companion")
print(f"O10 tracking effective companion: polar {len(osc_pol_eff)}, plate {len(osc_pla_eff)} -> G4_oscillation_tracking_effective.png")

# ===== s53/s54 CHRONOLOGICAL companions: the polar points come in PER-CELL groups taken across time =====
# The violin/scatter (above) hides that the N~800 polar points are NOT independent cells. These show the
# dots over time, ONE COLOUR PER CELL, so the per-cell time-grouping is visible. Plate-control overlaid in
# green when present (TrackMate spots, now on 4 MB).
def _cohort_shades(batches):
    """O8: single (1-Sister) = shades of blue, triple (3-Sister) = shades of orange (2/4-Sister get their
    own maps); shades within a classification separate the individual batches (base colour + shades)."""
    from collections import defaultdict as _dd
    grp=_dd(list)
    for b in batches: grp[b2.get(b)].append(b)
    base={"1-Sister":plt.cm.Blues,"3-Sister":plt.cm.Oranges,"2-Sister":plt.cm.Greens,"4-Sister":plt.cm.Purples}
    col={}
    for g,bs in grp.items():
        cmap=base.get(g,plt.cm.Greys)
        for i,b in enumerate(sorted(bs)): col[b]=cmap(0.45+0.5*(i/max(1,len(bs)-1)))
    return col
def _smooth_track(x,y,win=3):
    """USER 2026-08-05: "impose some version of the line-smoothing used in the lagging chromosome plots
    (as some of these lines jitter back and forth in a manner that i dont think is accurate)".

    The lagging figure (kt_shape_plots.lagging_since_anaphase) uses a MONOTONE ENVELOPE: keep only rising
    points before the track max and falling points after it. That is right for a lagging chromosome, which
    stretches to one peak and then shortens — it has a shape to impose. A polar KT's distance to the plate
    has no such single-peaked form (it can approach, sit, and approach again), so forcing a monotone
    envelope here would invent a trajectory rather than clean one. This applies the same INTENT — remove
    the frame-to-frame jitter, keep the real excursions — with a running median of `win` points, which
    deletes single-frame spikes without moving genuine multi-frame movement. Endpoints are kept as-is."""
    y=np.asarray(y,float)
    if y.size<win: return np.asarray(x,float),y
    h=win//2; out=y.copy()
    for i in range(h,y.size-h): out[i]=float(np.median(y[i-h:i+h+1]))
    return np.asarray(x,float),out

def _chrono(byb,bypla,ylab,ttl,fname,ymax=None,show_plate=True,anaphase_by_coh=None,group_note="",cell_colors=None,open_markers=None,
            drop_groups=None,trend_by_group=False,smooth=False):
    """drop_groups / trend_by_group: USER 2026-08-03 - "remove double ablation batches ... modify the plot so
    that each track is a shade according to if its 1 or 3 sisterless, and give a trendline to each"."""
    pid=fname[:-4]
    # per-plot manual removals (annotations/MANUAL_PLOT_EXCLUSIONS.csv) - a per-plot decision, never blanket
    _excl=lib.manual_plot_exclusions(pid)
    if _excl:
        for b in sorted(_excl & set(byb)):
            lib.log_review(pid,b,"","removed from this plot per MANUAL_PLOT_EXCLUSIONS.csv (user 2026-08-03)")
        byb={b:v for b,v in byb.items() if b not in _excl}
        bypla={b:v for b,v in (bypla or {}).items() if b not in _excl}
    if drop_groups:
        _dropped=sorted(b for b in byb if (b2.get(b) or "") in drop_groups)
        for b in _dropped:
            lib.log_review(pid,b,b2.get(b) or "?",f"group {b2.get(b)} dropped from this plot (user 2026-08-03)")
        byb={b:v for b,v in byb.items() if (b2.get(b) or "") not in drop_groups}
    figC,axC=plt.subplots(figsize=(8.8,5.4))
    cm=plt.cm.tab20(np.linspace(0,1,max(1,len(byb))))
    open_markers=open_markers or {}
    for (b,pts),col in zip(sorted(byb.items()),cm):
        if cell_colors is not None: col=cell_colors.get(b,col)   # O8: base-colour-by-classification + shades
        _gn=_SISNAME.get(b2.get(b),b2.get(b) or "?").split()[0]
        Pp=np.array(sorted(pts))
        _px,_py=(_smooth_track(Pp[:,0],Pp[:,1]) if smooth else (Pp[:,0],Pp[:,1]))
        axC.plot(_px,_py,color=col,alpha=.8,lw=1,marker="o",ms=3,label=f"{b[:22]} [{_gn}]")
        for _tm in open_markers.get(b,[]):   # O9: open marker sitting ON the line where an outlier point was removed
            _yy=float(np.interp(_tm,Pp[:,0],Pp[:,1])) if len(Pp)>=2 else (Pp[0,1] if len(Pp) else 0)
            axC.scatter([_tm],[_yy],facecolors="none",edgecolors=col,s=55,linewidths=1.4,zorder=6)
    _extra=[]
    # one linear trend per sisterless group, in that group's own colour (user 2026-08-03)
    if trend_by_group:
        _gpts=defaultdict(list)
        for b,pts in byb.items():
            g=b2.get(b) or "?"
            _gpts[g]+= [(t,v) for (t,v) in pts]
        for g in sorted(_gpts):
            P=np.array(sorted(_gpts[g]))
            if len(P)<4 or P[:,0].max()-P[:,0].min()<1e-9: continue
            m,c0=np.polyfit(P[:,0],P[:,1],1)
            xr=np.linspace(P[:,0].min(),P[:,0].max(),60)
            # the trend must carry the SAME hue family as that group's tracks (single=blue, triple=orange).
            # lib.PALETTE keys this plot's groups to unrelated colours (green/purple), which read as a third
            # and fourth series rather than as the trend of the blue/orange tracks.
            _gc={"1-Sister":plt.cm.Blues(0.95),"3-Sister":plt.cm.Oranges(0.95),
                 "2-Sister":plt.cm.Greens(0.95),"4-Sister":plt.cm.Purples(0.95)}.get(g,"#333")
            axC.plot(xr,m*xr+c0,color=_gc,ls="--",lw=2.8,zorder=8,
                     path_effects=[pe.Stroke(linewidth=4.4,foreground="white"),pe.Normal()])
            _gname=_SISNAME.get(g,g).split()[0]
            _extra.append(Line2D([0],[0],color=_gc,ls="--",lw=2.4,
                                 label=f"{_gname} trend (N={len(P)} pts, {len([b for b in byb if (b2.get(b) or '')==g])} cells)"))
    # ITEM 11: the oscillation chronological uses MANUAL polar annotations only -> no TrackMate plate overlay.
    if show_plate and bypla:
        for b,pts in sorted(bypla.items()):
            Pp=np.array(sorted(pts)); axC.plot(Pp[:,0],Pp[:,1],color=GREEN[0],alpha=.5,lw=1,marker="s",ms=3)   # unlabeled -> one legend handle below
        _extra.append(Line2D([0],[0],color=GREEN[0],lw=1,marker="s",ms=4,label="plate-control KTs (manual paired outlines)"))
    # ITEM 12: per-cohort anaphase-onset markers (only for groups still ON the plot - a dropped group must not
    # leave an orphan "double avg anaphase" line and legend entry behind)
    if anaphase_by_coh:
        _live={(b2.get(b) or "") for b in byb}
        anaphase_by_coh={g:v for g,v in anaphase_by_coh.items() if g in _live}
        for g,axm in sorted(anaphase_by_coh.items()):
            axC.axvline(axm,color=lib.PALETTE.get(g,"#888"),ls=(0,(5,2)),lw=1.5,alpha=.9)
            _extra.append(Line2D([0],[0],color=lib.PALETTE.get(g,"#888"),ls=(0,(5,2)),lw=1.5,label=f"{_SISNAME.get(g,g).split()[0]} avg anaphase"))
    axC.axvline(0,color="#333",ls=":",lw=.8)
    if ymax: axC.set_ylim(top=ymax)
    axC.set_xlabel("Time from metaphase onset (min; 0 = metaphase start, positive = after metaphase)"); axC.set_ylabel(ylab)
    _hc,_lc=axC.get_legend_handles_labels()
    if _hc or _extra: axC.legend(_hc+_extra,_lc+[h.get_label() for h in _extra],fontsize=6,ncol=1,loc="upper left",bbox_to_anchor=(1.01,1.0),title="cell [sisterless group]")   # legend OUTSIDE the axes (was over the tracks)
    # recompute the per-group N from what is ACTUALLY plotted; the caller's group_note is the global cohort
    # count and would still advertise a group this plot just dropped
    _cnt=_Counter((b2.get(b) or "?") for b in byb)
    _note=", ".join(f"{_SISNAME.get(k,k)} N={n}" for k,n in sorted(_cnt.items())) or group_note
    axC.set_title(f"{ttl} — by cell ({len(byb)} cells; {_note})",loc="left",fontweight="bold",fontsize=9.5)
    plt.tight_layout(); plt.savefig(f"{OUT}/{fname}",bbox_inches="tight"); plt.close()
    # data CSV (so exclusions/normalizations are DATA-verifiable, not appearance-only)
    _crows=[[b,(b2.get(b) or "?"),round(t,2),round(v,3)] for b,pts in byb.items() for (t,v) in pts]
    lib.record_plot(fname[:-4],["batch","sisterless_group","t_min_from_meta","value"],_crows,
        {"type":"per-cell line over time","excluded":f"{LONG_SAMPLE} (LONG_SAMPLE, ITEM6)","ylab":ylab},SCRIPT,ttl)
# (1) displacement per 20s over time — ITEM 11: MANUAL polar annotations only (20250401 already excluded via `cells`)
# O9 (2026-07-08 FIX): the OLD code removed only the 5 single greatest points, but a frame-mapping-glitch cell
# (e.g. 20260416 single ablati) contributes ~25 physically-impossible 12–16µm/20s steps, so 20 broken points
# still dominated the plot. Now apply the SAME >8µm tracking-glitch cap (OSC_HI) that G4_oscillation uses
# (standing rule: >8µm/20s = implausible tracking glitch) so EVERY implausible step is removed via the
# open-marker technique and logged (batch+timepoint) for the to-do list — matching the sister plot & readable.
_all_osc=[(b,tm,d) for (b,tm,d) in osc_pol_tv]
_glitch=[(b,tm,d) for (b,tm,d) in _all_osc if d>OSC_HI]          # OSC_HI=8.0, identical to G4_oscillation
_userflag=[(b,tm,d) for (b,tm,d) in _all_osc if lib.osc_point_excluded(b,tm)]   # explicit user-flagged outliers (removed everywhere)
_glitchset=set((b,round(tm,4)) for b,tm,d in _glitch)
_userset=set((b,round(tm,4)) for b,tm,d in _userflag)
_removeset=_glitchset|_userset
for b,tm,d in sorted(_glitch,key=lambda z:z[2],reverse=True):
    lib.log_review("oscillation_chrono_glitch_outlier",b,f"{d:.1f}µm/20s @ {tm:+.1f}min from meta",f"per-20s displacement >{OSC_HI}µm (implausible tracking/frame-mapping glitch) — REMOVED (open marker) from G4_oscillation_chronological; check this batch at this timepoint")
for b,tm,d in _userflag:
    lib.log_review("oscillation_outlier",b,f"{d:.2f}µm/20s @ {tm:+.1f}min from meta","user-flagged oscillation outlier — REMOVED everywhere")
OSC_CHRONO_EXCLUDE={"20250901 triple_ablation_11"}   # USER 2026-07-16: remove this sample from G4_oscillation_chronological
_byb=defaultdict(list); _open=defaultdict(list)
for (b,tm,d) in _all_osc:
    if b in OSC_CHRONO_EXCLUDE: continue
    if (b,round(tm,4)) in _removeset: _open[b].append(tm)
    else: _byb[b].append((tm,d))
_nrem=sum(len(v) for v in _open.values())   # dynamic count of removed points (glitch cap + user-flagged) shown as open markers
_bypla=defaultdict(list)
for (b,tm,d) in osc_pla_tv:
    if d<10: _bypla[b].append((tm,d))
_chrono(_byb,_bypla,"Displacement per 20s interval (µm)",f"Polar-KT displacement per 20s over time (manual annotations; {_nrem} implausible/flagged points removed to open markers)","G4_oscillation_chronological.png",ymax=None,show_plate=False,group_note=SIS_GROUPS_LABEL,open_markers=_open)
# (2) distance-to-plate over time (from recD; polar already anchored AFTER metaphase => starts at t=0)
_byb2=defaultdict(list); _pl2=defaultdict(list)
for r in recD:
    (_pl2 if r[1]=="plate" else _byb2)[r[0]].append((r[2],r[3]))
# ITEM 12: per-cohort average anaphase onset (min after metaphase) for the plotted cells
_ana_by_coh={}
for b in _byb2:
    g=b2.get(b); _m=lib.parse_time(mr.get(b,{}).get("Metaphase Start (s)","")); _a=lib.parse_time(mr.get(b,{}).get("Anaphase Onset (s)",""))
    if g and _m is not None and _a is not None and _a>_m: _ana_by_coh.setdefault(g,[]).append((_a-_m)/60.0)
_ana_by_coh={g:float(np.median(v)) for g,v in _ana_by_coh.items() if v}  # USER 2026-08-10: MEDIAN, not mean
# O8: colour cells by ablation classification (single=blue shades, triple=orange shades) so single vs triple is legible
_dist_colors=_cohort_shades(list(_byb2.keys()))
# USER 2026-08-03: drop the double (2-sisterless) batches, shade each track by 1- vs 3-sisterless, and give
# each of those two groups its own trendline. The wildly oscillating orange track
# (20250909 triple_ablation_collagen_3) is removed via MANUAL_PLOT_EXCLUSIONS.csv inside _chrono().
_chrono(_byb2,_pl2,"Distance to metaphase plate (µm)","Polar-KT distance-to-plate over time (single=blue shades, triple=orange shades)","G4_plate_distance_chronological.png",show_plate=True,anaphase_by_coh=_ana_by_coh,group_note=SIS_GROUPS_LABEL,cell_colors=_dist_colors,
        drop_groups={"2-Sister"},trend_by_group=True,smooth=True)
print(f"chronological (s53/s54): oscillation {len(_byb)} cells, distance {len(_byb2)} cells")

# ===== S49: eYFP-Cdc20 intensity vs distance-from-plate — SAME r=5 bg-subtracted method for BOTH groups =====
cyto=defaultdict(list)
for r in csv.DictReader(open(f"{ANN}/kt_points.csv")):
    if lib.is_prophase_ablation(r.get("batch","")): continue   # prophase excluded (no prophase group)
    if r["label"]=="cytosol_bg":
        try: cyto[r["batch"].strip()].append((float(r["t_sec"]),float(r["x"]),float(r["y"])))
        except: pass
R=int(os.environ.get("KT_R","9"))   # measurement radius — standard r=9 (lib.disk_sum default); deck may override via KT_R
def r9_bg(g,x,y,b,t):
    """SAME for polar & plate: intact KT snapped to punctum, minus the marked cytosol disk (same frame)."""
    cb=cyto.get(b)
    if not cb: return None
    _bt,bx,by=min(cb,key=lambda c:abs(c[0]-t)); cval=lib.disk_sum(g,bx,by,R)   # marked cytosol bg (no snap)
    if cval is None: return None
    sx,sy=lib.snap_to_peak(g,x,y)                                            # intact KT -> snap to punctum
    if lib.is_saturated(g,sx,sy,R) or lib.is_saturated(g,bx,by,R): return None  # clipped pixel -> unquantifiable
    return max(0.0, lib.disk_sum(g,sx,sy,R)-cval)   # FLOOR at 0: no negative fluorescence (over-subtracted bg = 0 signal)
DPOL=[];IPOL=[];DPLA=[];IPLA=[]; sane=[]
POL_BTI=[]; PLA_BTI=[]   # ITEM 10: (batch,t_sec,intensity) per KT for same-frame polar<->plate pairing
for b in cells:
    ft=lib.FluorTif(b,'monitoring')                         # 16-bit cropped fluor TIF (validated vs MP4)
    if not ft.ok(): continue
    pxs=ps(b); c,n=plate_axis(plate[b])
    if abs(pxs-0.031)<0.005:                                 # KNOWN ISSUE: non-uniform pixel size — flag 0.031 batches in distance/intensity plots
        lib.log_review("pixel_size_0p031",b,f"{pxs:.3f}","0.031 µm/px batch entering distance/intensity plot — verify scale")
    def grab(t): return ft.plane_at(t)
    for t,x,y,fr in sorted(polar[b]):
        g=ft.plane_by_frame(fr)                              # polar KTs move -> map by FRAME (ground-truth), not t_sec
        if g is None: continue
        I=r9_bg(g,x,y,b,t)
        if I is not None: DPOL.append(dist_px((x,y),c,n)*pxs); IPOL.append(I); POL_BTI.append((b,t,I))
    # plate controls are now MANUAL paired-KT outlines, so the 4th field is the FRAME index, not a TrackMate
    # intensity. Map by FRAME (ground truth) exactly as the polar branch above does - frames.json t_sec is
    # shifted 1-2 frames, so grabbing by time would sample the wrong plane.
    for (t,x,y,fr) in plate_spots.get(b,[]):
        g=ft.plane_by_frame(fr)
        if g is None: continue
        I=r9_bg(g,x,y,b,t)
        if I is not None:
            DPLA.append(dist_px((x,y),c,n)*pxs); IPLA.append(I); PLA_BTI.append((b,t,I))
    ft.close()
# audio S49: the user flagged the single super-bright plate point — exclude THAT point (the brightest).
# Note: it is NOT a statistical outlier (top plate intensities form a smooth cluster, max modified-z≈1.6
# at both r=5 and r=9); excluded purely because the user explicitly pointed at it (standing rule).
_sb_excluded=0
if IPLA:
    _a=np.array(IPLA,float); _med=np.median(_a); _mad=np.median(np.abs(_a-_med)) or 1.0
    _imax=int(np.argmax(_a)); _z=0.6745*(_a[_imax]-_med)/_mad
    print("S49 plate intensities top-8:",[round(v) for v in sorted(_a,reverse=True)[:8]],"| med",round(_med),"| brightest modified-z",round(float(_z),1))
    lib.log_review("cdc20_plate_superbright_excluded","tracking_dist",f"I={_a[_imax]:.0f} (brightest plate KT, z={_z:.1f})","user-flagged super-bright plate KT EXCLUDED per audio S49 (not a statistical outlier)")
    _sb_excluded=1; _keep=[i for i in range(len(IPLA)) if i!=_imax]
    DPLA=[DPLA[i] for i in _keep]; IPLA=[IPLA[i] for i in _keep]; PLA_BTI=[PLA_BTI[i] for i in _keep]
    if sane: sane=[sane[i] for i in _keep]   # `sane` is only populated while a TrackMate intensity exists
# (a) intensity vs distance — ITEM 8: G4_cdc20_vs_distance REMOVED (redundant with G4_distance_vs_fluor
# below, which plots the same per-KT-per-frame intensity vs distance with separate polar/plate trendlines
# and a paired companion). Generation disabled; orchestrator drops G4_cdc20_vs_distance from the manifest.
# (block intentionally not rendered)
# (a2) CD3: G4_distance_vs_fluor (per-KT-per-frame fluorescence vs distance-from-plate) is RETIRED per
# 07-07 feedback (raw 300): "this plot is not correct and we should have essentially the same data plotted
# using our manual points on an earlier slide, so confirm and then retire this plot." The manual-points
# equivalent is the eYFP-Cdc20 polar-vs-plate work in group4_cdc20_poles.py (owned by another agent).
# The FIGURE + record_plot are disabled; the measurement loop above is KEPT because the paired plot (CD4,
# below) reuses POL_BTI / PLA_BTI. Orchestrator: drop G4_distance_vs_fluor from the manifest/deck.
from scipy import stats as _stDF   # still used by the paired plot (Wilcoxon/Spearman)
# (a2-REVIVED 2026-07-10, user): G4_distance_vs_fluor UN-RETIRED. It is genuinely distinct from
# G4_fluor_vs_duration (that = whole-CELL fluor vs metaphase DURATION); this = per-KT eYFP-Cdc20 intensity vs
# the KT's DISTANCE from the metaphase plate — the only view of the continuous distance<->intensity relationship
# (the manual polar-vs-plate plots are CATEGORICAL, not vs continuous distance). CAVEAT (the 07-07 "not correct"
# flag): polar KTs are MANUAL points, plate KTs are MANUAL paired-outline centroids; both measured IDENTICALLY (r9_bg:
# snapped to punctum, marked-cytosol-bg-subtracted, floored at 0). Provenance is shown in the legend.
figDF,axDF=plt.subplots(figsize=(6.8,5.4)); _rowsDF=[]
def _dfTrend(ax,xs,ys,color,label):
    xs=np.asarray(xs,float); ys=np.asarray(ys,float)
    if len(xs)>=3 and np.unique(xs).size>=2:
        lr=_stDF.linregress(xs,ys); xln=np.array([xs.min(),xs.max()])
        ax.plot(xln,lr.intercept+lr.slope*xln,color=color,lw=1.8,ls="--",alpha=.9,zorder=2)
        try: rho,pv=_stDF.spearmanr(xs,ys); return f"{label}: N={len(xs)}, Spearman ρ={rho:.2f} p={pv:.2g}"
        except Exception: pass
    return f"{label}: N={len(xs)}"
axDF.scatter(DPLA,IPLA,s=16,color=GREEN[0],alpha=.55,edgecolor="white",lw=.3,zorder=3,label="plate KT (manual paired-outline pos)")
axDF.scatter(DPOL,IPOL,s=16,color=PURPLE[0],alpha=.7,edgecolor="white",lw=.3,zorder=3,label="polar KT (manual)")
_tpla=_dfTrend(axDF,DPLA,IPLA,GREEN[0],"plate"); _tpol=_dfTrend(axDF,DPOL,IPOL,PURPLE[0],"polar")
for _d,_I in zip(DPOL,IPOL): _rowsDF.append(["polar",round(_d,3),round(_I,1)])
for _d,_I in zip(DPLA,IPLA): _rowsDF.append(["plate",round(_d,3),round(_I,1)])
axDF.set_xlabel("Distance from metaphase plate (µm)")
axDF.set_ylabel(f"eYFP-Cdc20 intensity (Σ r={R} disk, bg-subtracted)")
axDF.set_title(f"eYFP-Cdc20 intensity vs distance from metaphase plate\n{_tpol}  ·  {_tpla}",loc="left",fontweight="bold",fontsize=8.8)
axDF.legend(fontsize=8,loc="best")
plt.tight_layout(); plt.savefig(f"{OUT}/G4_distance_vs_fluor.png",bbox_inches="tight"); plt.close()
lib.record_plot("G4_distance_vs_fluor",["group","distance_um","intensity_bgsub"],_rowsDF,
  {"type":"scatter polar+plate vs distance-from-plate, per-group Spearman + linear trend",
   "measure":f"r={R} disk Σ bg-subtracted (snapped, marked-cytosol bg, floored 0)",
   "provenance":"polar=manual points, plate=MANUAL paired-outline centroids",
   "note":"un-retired 2026-07-10 per user; distinct from G4_fluor_vs_duration (cell fluor vs duration)"},
  SCRIPT,"eYFP-Cdc20 intensity vs KT distance from metaphase plate (polar + plate)")
print(f"a2-REVIVED: G4_distance_vs_fluor -> polar N={len(DPOL)}, plate N={len(DPLA)}")

# ITEM 10 (paired companion): each polar KT paired with the same-cell plate-control KT NEAREST IN TIME
# (same/adjacent frame). Both measured identically (r=9 disk Σ, cytosol-bg-subtracted, snapped). Paired
# Wilcoxon signed-rank tests whether polar > its own-frame plate — the fair within-frame comparison.
_polb=defaultdict(list); _plab=defaultdict(list)
for _b,_t,_I in POL_BTI: _polb[_b].append((_t,_I))
for _b,_t,_I in PLA_BTI: _plab[_b].append((_t,_I))
_TOLp=45.0   # seconds: pair to the plate KT within ~one frame interval
_pairs=[]    # (plate_I, polar_I, batch)
for _b in _polb:
    if _b not in _plab: continue
    _pl=sorted(_plab[_b])
    for _t,_Ip in _polb[_b]:
        _tt,_Iq=min(_pl,key=lambda z:abs(z[0]-_t))
        if abs(_tt-_t)<=_TOLp: _pairs.append((_Iq,_Ip,_b))
# CD4: flag + REMOVE pairs where fluorescence DECREASES from plate to paired polar (polar dimmer than its
# same-frame plate control) — user will review these separately.
_pairs_all=_pairs; _pairs=[]; _cd4_removed=0
for _Iq,_Ip,_b in _pairs_all:
    if _Ip<_Iq:
        _cd4_removed+=1
        lib.log_review("cdc20_paired_polar_dimmer",_b,f"polar {_Ip:.0f} < plate {_Iq:.0f}","CD4: paired sample where eYFP-Cdc20 DECREASES plate->polar (polar dimmer than its same-frame plate control) — REMOVED from G4_distance_vs_fluor_paired; review later")
    else:
        _pairs.append((_Iq,_Ip,_b))
print(f"CD4: removed {_cd4_removed} plate->polar-decreasing pairs; {len(_pairs)} pairs kept")
figP,axP=plt.subplots(figsize=(6.2,5.6)); _rowsP=[]
if _pairs:
    _plv=np.array([p[0] for p in _pairs],float); _pov=np.array([p[1] for p in _pairs],float)
    _rng=np.random.RandomState(0)
    for _pv,_ov in zip(_plv,_pov):
        axP.plot([0,1],[_pv,_ov],color=(PURPLE[1] if _ov>_pv else "#cccccc"),alpha=.35,lw=.7,zorder=1)
    axP.scatter(np.zeros(len(_plv))+(_rng.rand(len(_plv))-.5)*.12,_plv,s=14,color=GREEN[0],alpha=.6,zorder=3)
    axP.scatter(np.ones(len(_pov))+(_rng.rand(len(_pov))-.5)*.12,_pov,s=14,color=PURPLE[0],alpha=.6,zorder=3)
    axP.hlines(np.median(_plv),-.22,.22,color=GREEN[0],lw=2.6,zorder=4); axP.hlines(np.median(_pov),.78,1.22,color=PURPLE[0],lw=2.6,zorder=4)
    _frac=float(np.mean(_pov>_plv))
    try: _W,_pw=_stDF.wilcoxon(_pov,_plv,alternative="greater"); _pwr=f"Wilcoxon (polar>plate, paired) p={_pw:.2g}"
    except Exception: _pwr="Wilcoxon n/a"
    axP.set_title(f"eYFP-Cdc20 — polar vs SAME-FRAME plate KT (paired)\n{_pwr}; polar brighter in {_frac*100:.0f}% of {len(_pairs)} pairs (med polar {np.median(_pov):,.0f} vs plate {np.median(_plv):,.0f}); {_cd4_removed} plate>polar pairs removed for review (CD4)",loc="left",fontweight="bold",fontsize=8.6)
    for _pv,_ov,_bb in _pairs: _rowsP.append([_bb,round(_pv,1),round(_ov,1)])
else:
    axP.set_title("polar vs same-frame plate (paired) — no pairs within tolerance",loc="left",fontweight="bold",fontsize=9)
axP.set_xticks([0,1]); axP.set_xticklabels(["plate-control KT","polar KT\n(same frame, same cell)"])
axP.set_ylabel(f"eYFP-Cdc20 intensity (Σ r={R} disk, bg-subtracted)")
plt.tight_layout(); plt.savefig(f"{OUT}/G4_distance_vs_fluor_paired.png",bbox_inches="tight"); plt.close()
lib.record_plot("G4_distance_vs_fluor_paired",["batch","plate_I","polar_I"],_rowsP,
  {"type":"paired dumbbell + Wilcoxon signed-rank (polar>plate)","pairing":f"polar KT <-> same-cell plate-control KT nearest in time (<= {_TOLp:.0f}s)","measure":f"r={R} disk Σ bg-subtracted, both groups identical"},
  SCRIPT,"Paired polar vs same-frame plate-control eYFP-Cdc20 intensity")
print(f"I10 paired: {len(_pairs)} polar<->plate same-frame pairs -> G4_distance_vs_fluor_paired.png")
# (b) s55 sanity check: OUR r=9 bg-subtracted disk Σ (measured on the 16-bit cropped fluor TIF) vs
# TrackMate's own reported total_intensity, at the SAME spot positions. The two are EXPECTED to differ in
# absolute value (different measurement models — see RETURN): we only expect a monotonic relationship, so
# we report Spearman ρ, not a slope of 1.
# 2026-08-03: the plate-control series moved to MANUAL paired-KT outlines (user: manual annotations override
# TrackMate), so there is no TrackMate intensity paired with these spots any more and `sane` is empty. The
# figure is therefore NOT regenerated. Say so out loud rather than leaving a stale PDF that silently claims
# to validate a source the plots no longer use. It is not placed in META or supplemental.
if not sane:
    print("s55 sanity: SKIPPED — plate controls are manual outlines now, so no TrackMate intensity to compare; "
          "G4_cdc20_intensity_sanitycheck not regenerated (its existing PDF is stale, and is not placed in either deck)")
    lib.log_review("cdc20_intensity_sanitycheck","(all)","",
                   "s55 TrackMate-vs-ours sanity plot unfed after the 2026-08-03 switch to manual paired-KT "
                   "plate controls; figure not regenerated - retire it or re-source it from TrackMate directly")
if len(sane)>=5:
    fig4,ax4=plt.subplots(figsize=(6.6,6.4))
    tmv=[s[0] for s in sane]; r9v=[s[1] for s in sane]
    ax4.scatter(tmv,r9v,s=12,alpha=.5,color="#333")
    from scipy import stats as _st2; _rho,_p=_st2.spearmanr(tmv,r9v)
    ax4.set_xlabel("TrackMate total_intensity (TrackMate's own model)")
    ax4.set_ylabel(f"Our r={R} disk Σ, bg-subtracted (16-bit fluor TIF)")
    ax4.set_title(f"s55 sanity — our r={R} disk Σ vs TrackMate intensity\nSpearman ρ={_rho:.2f} (p={_p:.1g}), N={len(sane)}; differ in absolute scale, monotonic",loc="left",fontsize=9)
    # ITEM 9: on-figure explanatory paragraph — what the two measurements are and how they were obtained.
    _para=("What is plotted: each dot is one plate-control kinetochore spot, compared two ways. "
      "X = TrackMate's own reported total_intensity — the signal TrackMate integrates over the spot it "
      "detected and tracked (its built-in spot/quality model), read straight from the tracking output. "
      f"Y = our independent measure: at that same spot position we sum every pixel value inside a radius-{R} "
      "disk on the 16-bit cropped fluorescence TIF (spot first snapped to the local punctum peak), then "
      "subtract a same-radius cytosol-background disk sampled on the same frame (the marked 'cytosol_bg' "
      "point). The two use different integration areas and background handling, so their absolute values "
      f"differ; we therefore test only for a monotonic relationship. Spearman ρ={_rho:.2f} (N={len(sane)}) "
      "confirms our manual disk measurement reproduces TrackMate's kinetochore-to-kinetochore intensity "
      "ranking — validating the disk-Σ method used in the other eYFP-Cdc20 intensity figures. "
      "Why TrackMate is consistently HIGHER: TrackMate's total_intensity integrates the raw spot pixels "
      "WITHOUT subtracting the local cytosol background, whereas our disk-Σ subtracts a same-radius "
      "marked-cytosol disk on each frame — so TrackMate runs higher by roughly the cytosol offset; only "
      "the monotonic (rank) relationship is expected to match, not the absolute scale.")
    fig4.subplots_adjust(bottom=0.32)
    fig4.text(0.02,0.02,_para,ha="left",va="bottom",fontsize=7.2,wrap=True)
    plt.savefig(f"{OUT}/G4_cdc20_intensity_sanitycheck.png",bbox_inches="tight"); plt.close()
    lib.record_plot("G4_cdc20_intensity_sanitycheck",["trackmate_total_intensity","our_r9_disk_sum_bgsub"],
        [[round(s[0],2),round(s[1],2)] for s in sane],
        {"type":"scatter (validation)","stat":f"Spearman rho={_rho:.3f}, p={_p:.2g}, N={len(sane)}"},SCRIPT,
        "Sanity check: our disk-Σ vs TrackMate intensity")
    print(f"s55 sanity: our r={R} disk Σ (from TIF) vs TrackMate Spearman rho={_rho:.2f} N={len(sane)}")
print(f"S49 intensity-vs-distance: polar N={len(IPOL)}, plate N={len(IPLA)} | S49 super-bright plate excluded: {_sb_excluded}")
lib.flush_review("/Volumes/4 MB/ablation_figures_20260625/_review/outlier_review_tracking.csv")
