#target illustrator
app.userInteractionLevel = UserInteractionLevel.DONTDISPLAYALERTS;
var COPY="/Volumes/4 MB/ablation_plots/_superseded_decks/ablation_figures_grouped copy.ai";
var d=null; for(var q=0;q<app.documents.length;q++){if(app.documents[q].name=="ablation_figures_grouped copy.ai"){d=app.documents[q];break;}}
var opened=false; if(!d){d=app.open(new File(COPY));opened=true;}
function baseOf(pi){var f=null;try{f=pi.file;}catch(e){}if(!f)return null;return decodeURI(f.name).toLowerCase().replace(/\.(pdf|png|svg)$/,"");}
var T=["1-sisterless_candidates", "1-sisterless_candidates_2", "2-sisterless_candidates", "3-sisterless_candidates", "DEMO_area_with_timestrips", "G1_traced_timestrip", "G3_slippage_timestrip_colcemid", "G3_slippage_timestrip_colcemid_aligned", "G3_slippage_timestrip_nocodazole", "G3_slippage_timestrip_nocodazole_aligned", "G4_polar_timestrip_20250403_ptk_yfpcdc20_22", "G4_polar_timestrip_20250403_ptk_yfpcdc20_22_aligned", "G4_polar_timestrip_20250410_ptk_yfpcdc20_11", "G4_polar_timestrip_20250410_ptk_yfpcdc20_11_aligned", "G4_polar_timestrip_20260416_single_ablation_10", "G4_polar_timestrip_20260416_single_ablation_10_aligned", "G4_polar_timestrip_20260416_single_ablation_15", "G4_polar_timestrip_20260416_single_ablation_15_aligned", "G5_hec1_mad1_dot_quant", "G5_item4_hec1_timestrip_xy2", "G5_item4_hec1_timestrip_xy4", "G5_item4_hec1_timestrip_xy5", "G5_item4_hec1_timestrip_xy6", "G5_mad1_timestrip_20260303_Mad1_Ptk_Eyfpcdc2_ablation_1metaphase_52", "G5_mad1_timestrip_20260303_Mad1_Ptk_Eyfpcdc2_ablation_1metaphase_52_aligned", "G5_mad1_timestrip_20260303_Mad1_Ptk_Eyfpmad1_ablation_10", "G5_mad1_timestrip_20260303_Mad1_Ptk_Eyfpmad1_ablation_10_aligned", "G5_mad1_timestrip_20260304_Mad1_timelapse_1_xy6", "G5_mad1_timestrip_20260304_Mad1_timelapse_2_xy1", "G5_mad1_timestrip_20260304_Mad1_timelapse_2_xy10", "G5_mad1_timestrip_20260310_ptk2_eyfp_mad1_14", "G5_mad1_timestrip_20260310_ptk2_eyfp_mad1_14_aligned", "G9_drug_timestrip_noc", "G9_drug_timestrip_noc_aligned", "G9_drug_timestrip_zm", "G9_drug_timestrip_zm3", "G9_drug_timestrip_zm3_aligned", "G9_drug_timestrip_zm_aligned", "double-chromosome_candidates", "frap_candidates", "frap_candidates_2", "frap_candidates_3", "off-target_candidates", "off-target_candidates_2", "polar_candidates", "polar_candidates_2", "polar_candidates_3", "unmanipulated_candidates"]; var want={}; for(var i=0;i<T.length;i++) want[T[i].toLowerCase()]=true;
var n=0; for(var i=0;i<d.placedItems.length;i++){var pi=d.placedItems[i]; var b=baseOf(pi);
  if(b&&want[b]){ try{ var cur=pi.file; if(cur&&cur.exists){ pi.file=new File(cur.fsName); n++; } }catch(e){} } }
var so=new IllustratorSaveOptions(); so.pdfCompatible=false; d.saveAs(new File(COPY),so);
if(opened){d.close(SaveOptions.DONOTSAVECHANGES);}
"RELOADED "+n+" of "+T.length;
